# Model Comparison

In [1]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Baseline XGBoost",
        "Graph Enhanced XGBoost"
    ],
    "MAE": [
        47.12,
        31.49
    ],
    "RMSE": [
        108.40,
        90.92
    ],
    "R2": [
        0.9297,
        0.9506
    ],
    "Accuracy_15pct": [
        0,
        54.46
    ]
})

comparison

                    Model    MAE    RMSE      R2  Accuracy_15pct
0        Baseline XGBoost  47.12  108.40  0.9297            0.00
1  Graph Enhanced XGBoost  31.49   90.92  0.9506           54.46

In [2]:
comparison["MAE_Improvement_%"] = (
    (
        47.12 - comparison["MAE"]
    )
    / 47.12
    * 100
)

comparison

,Model,MAE,RMSE,R2,Accuracy_15pct,MAE_Improvement_%
0,Baseline XGBoost,47.12,108.40,0.9297,0.00,0.000000
1,Graph Enhanced XGBoost,31.49,90.92,0.9506,54.46,33.170628

In [3]:
comparison.to_csv(
    r"D:\Projects\Delivery_ETA\outputs\model_comparison.csv",
    index=False
)

comparison

,Model,MAE,RMSE,R2,Accuracy_15pct,MAE_Improvement_%
0,Baseline XGBoost,47.12,108.40,0.9297,0.00,0.000000
1,Graph Enhanced XGBoost,31.49,90.92,0.9506,54.46,33.170628

In [4]:
print(
    "MAE Improvement:",
    round(
        ((47.12 - 31.49) / 47.12) * 100,
        2
    ),
    "%"
)

MAE Improvement: 33.17 %